version: '2'
services:
    tag-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        command: mongos --configdb tag-mongodb-config
    tag-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    tag-mongodb-config:
        image: mongo:3.4.10
        container_name: tag-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
