apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: security
  namespace: blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: security-app
        image: blog-graphql-ms/security
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:${jhipster.registry.password}@jhipster-registry.blog.svc.cluster.local:8761/config
        - name: JHIPSTER_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: registry-secret
              key: registry-admin-password
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:${jhipster.registry.password}@jhipster-registry.blog.svc.cluster.local:8761/eureka/
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://security-postgresql.blog.svc.cluster.local:5432/security
        - name: JHIPSTER_METRICS_LOGS_ENABLED
          value: 'true'
        - name: JHIPSTER_LOGGING_LOGSTASH_ENABLED
          value: 'true'
        - name: JHIPSTER_LOGGING_LOGSTASH_HOST
          value: jhipster-logstash
        - name: SPRING_ZIPKIN_ENABLED
          value: "true"
        - name: SPRING_ZIPKIN_BASE_URL
          value: http://jhipster-zipkin
        - name: JHIPSTER_METRICS_PROMETHEUS_ENABLED
          value: 'true'
        - name: JHIPSTER_METRICS_PROMETHEUS_ENDPOINT
          value: /prometheusMetrics
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: web
          containerPort: 9999
        readinessProbe:
          httpGet:
            path: /management/health
            port: web
        livenessProbe:
          httpGet:
            path: /management/health
            port: web
          initialDelaySeconds: 180

