version: '2'
services:
    author-app:
        image: author
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://author-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=author
            - JHIPSTER_SLEEP=30
            - JAVA_OPTS=-XX:InitialHeapSize=256m -XX:MaxHeapSize=256m
                -XX:MaxMetaspaceSize=100m -XX:CompressedClassSpaceSize=100m
                -XX:+AlwaysPreTouch -XX:+UseLargePages -XX:+UseG1GC
                -XX:+UseStringDeduplication
            - JHIPSTER_REGISTRY_PASSWORD=admin
    author-mongodb:
        image: mongo:3.4.10
    
    blog-app:
        image: blog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - JHIPSTER_SLEEP=30
            - JAVA_OPTS=-XX:InitialHeapSize=256m -XX:MaxHeapSize=256m
                -XX:MaxMetaspaceSize=100m -XX:CompressedClassSpaceSize=100m
                -XX:+AlwaysPreTouch -XX:+UseLargePages -XX:+UseG1GC
                -XX:+UseStringDeduplication
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8080:8080
    
    comment-app:
        image: comment
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://comment-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=comment
            - JHIPSTER_SLEEP=30
            - JAVA_OPTS=-XX:InitialHeapSize=256m -XX:MaxHeapSize=256m
                -XX:MaxMetaspaceSize=100m -XX:CompressedClassSpaceSize=100m
                -XX:+AlwaysPreTouch -XX:+UseLargePages -XX:+UseG1GC
                -XX:+UseStringDeduplication
            - JHIPSTER_REGISTRY_PASSWORD=admin
    comment-mongodb:
        image: mongo:3.4.10
    
    post-app:
        image: post
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://post-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=post
            - JHIPSTER_SLEEP=30
            - JAVA_OPTS=-XX:InitialHeapSize=256m -XX:MaxHeapSize=256m
                -XX:MaxMetaspaceSize=100m -XX:CompressedClassSpaceSize=100m
                -XX:+AlwaysPreTouch -XX:+UseLargePages -XX:+UseG1GC
                -XX:+UseStringDeduplication
            - JHIPSTER_REGISTRY_PASSWORD=admin
    post-mongodb:
        image: mongo:3.4.10
    
    security-app:
        image: security
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://security-postgresql:5432/security
            - JHIPSTER_SLEEP=30
            - JAVA_OPTS=-XX:InitialHeapSize=256m -XX:MaxHeapSize=256m
                -XX:MaxMetaspaceSize=100m -XX:CompressedClassSpaceSize=100m
                -XX:+AlwaysPreTouch -XX:+UseLargePages -XX:+UseG1GC
                -XX:+UseStringDeduplication
            - JHIPSTER_REGISTRY_PASSWORD=admin
    security-postgresql:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=security
            - POSTGRES_PASSWORD=
    
    tag-app:
        image: tag
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://tag-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=tag
            - JHIPSTER_SLEEP=30
            - JAVA_OPTS=-XX:InitialHeapSize=256m -XX:MaxHeapSize=256m
                -XX:MaxMetaspaceSize=100m -XX:CompressedClassSpaceSize=100m
                -XX:+AlwaysPreTouch -XX:+UseLargePages -XX:+UseG1GC
                -XX:+UseStringDeduplication
            - JHIPSTER_REGISTRY_PASSWORD=admin
    tag-mongodb:
        image: mongo:3.4.10
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
