apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: author-app
  namespace: blog
  labels:
    team: blog
spec:
  selector:
    matchLabels:
      app: author
  endpoints:
  - port: web
    path: /prometheusMetrics
