version: '2'
services:
    security-app:
        image: security
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://security-postgresql:5432/security
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - JAVA_OPTS=-XX:InitialHeapSize=256m -XX:MaxHeapSize=256m -XX:MaxMetaspaceSize=100m -XX:CompressedClassSpaceSize=100m -XX:+AlwaysPreTouch -XX:+UseLargePages -XX:+UseG1GC -XX:+UseStringDeduplication
    security-postgresql:
        extends:
            file: postgresql.yml
            service: security-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
