version: '2'
services:
    security-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/security/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=security
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
